name: Telegram News Bot

on:
  push:
    branches:
      - main  # main 브랜치로 push될 때 실행
  schedule:
    - cron: '0 * * * *'  # 매시간 실행 (UTC 기준)
  workflow_dispatch:  # 수동 실행 가능

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests beautifulsoup4

      - name: Run Scraper
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python crawler_telegram.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add sent_articles.json
          git commit -m "Update sent articles" || echo "No changes to commit"
          git push origin main
        continue-on-error: true
