
name: 9to5Mac Web Scraper

on:
  push:
    branches:
      - main  # main 브랜치로 push될 때 실행
  schedule:
    - cron: '0 6 * * *'  # 매일 6AM UTC (한국시간 3PM)에 실행

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Scraper
        run: python crawler.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add scraped_data.json
          git commit -m "Auto-update scraped data"
          git push
        continue-on-error: true  # 변경사항이 없으면 에러 방지
