name: Telegram News Bot with Personal & Group Chats

on:
  push:
    branches:
      - main
  #schedule:
  #  - cron: '0 * * * *'  # 매시간 실행 (UTC 기준)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests beautifulsoup4

      - name: Run Scraper
        env:
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_CHAT_ID_GROUP: ${{ secrets.TELEGRAM_CHAT_ID_GROUP }}
        run: python crawler_telegram.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add sent_articles.json
          git commit -m "Update sent articles" || echo "No changes to commit"
          git push origin main
        continue-on-error: true
